name: Auto-Back-Merge
description: "Automatically create a back merge PR when pushing to the production branch."
author: "chimiketsu"
branding:
  icon: file-text
  color: purple

inputs:
  head:
    description: "A production branch name"
    default: main
    required: true
  base:
    description: "A develop branch name"
    default: develop
    required: true
  slack_token:
    description: "A Slack bot token"
    default: ""
    required: false
  slack_channel:
    description: "A Slack channel ID where you want to post a message"
    default: ""
    required: false

runs:
  # タスクを再利用できるようにする
  using: "composite"
  steps:
    # master → developにバックマージするPRを作成する
    - name: Create back merge pull request
      run: ${{ github.action_path }}/main
      shell: bash
      env:
        REPOSITORY:   ${{ github.repository }}
        PR:           ${{ github.event.number }}
        GITHUB_TOKEN: ${{ github.token }}

        HEAD:          ${{ inputs.head }}
        BASE:          ${{ inputs.base }}
        SLACK_TOKEN:   ${{ inputs.slack_token }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
